name: lint

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

env:
  SRC_DIR: zxlive

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    continue-on-error: true
    steps:
    - uses: actions/checkout@v6
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run:
        pip install ".[test]"
    - name: mypy
      run:
        mypy zxlive
    - name: Ruff Check
      run:
        ruff check
