name: lint

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

env:
  SRC_DIR: zxlive

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependecies
      run:
        pip install ".[test]"
    - name: mypy
      run:
        mypy zxlive
    - name: Flake8
      continue-on-error: true
      run:
        pflake8 zxlive
    - name: Pylint
      continue-on-error: true
      run:
        pylint zxlive
