name: lint

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

env:
  SRC_DIR: zxlive

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install ".[test]"
      - run: mypy zxlive

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install ruff
      - run: ruff check

  code-complexity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install ruff complexipy
      - name: Ruff - Cyclomatic Complexity
        if: always()
        run: ruff check . --select=PLR0912
      - name: Complexipy - Cognitive Complexity
        if: always()
        run: complexipy . --max-complexity-allowed 15
